nombres = [
    "Tierra, Territorio y Ecosistemas de las Comunidades Rurales",
    "Lo Rural, las Ruralidades y las Poblaciones Rurales",
    "El Buen Vivir: Vivir Bien en el Territorio y la Comunidad",
    "Pedagogías desde la Diversidad Cultural",
    "Cartografía Social y Territorial",
    "Lectura, Escritura y Oralidad: prácticas culturales I",
    "Características y Condiciones Agroambientales del territorio",
    "Campesinas y Campesinos como Sujetos de Derechos",
    "Trayectorias de vida y relaciones intrafamiliares e intergeneracionales",
    "Pedagogías Críticas, Creativas y Decoloniales",
    "Espiritualidad, Saberes y Prácticas Culturales en el Territorio",
    "Lectura, Escritura y Oralidad: prácticas culturales II",
    "Geopolítica, Extractivismo y Conflictos Territoriales",
    "Liderazgo y Participación para la Gobernanza Territorial",
    "Soberanía Alimentaria y Agroecología",
    "Educación y Género en la Ruralidad",
    "Ética en el trabajo con la comunidad",
    "Periodismo y Radio Comunitaria",
    "Sistemas de Información sobre la Ruralidad",
    "Ordenamiento Territorial y Sistemas de Planeación",
    "Salud Mental Comunitaria y Prácticas de Cuidado en la Ruralidad",
    "Metodologías para el trabajo educativo en la ruralidad",
    "Práctica Pedagógica I: Investigación Acción Participativa",
    "Programas educativos a través de medios digitales",
    "Gestión y Manejo de Sistemas Productivos y Ambientales en la Ruralidad",
    "Reforma Rural Integral y Construcción de Paz Territorial",
    "Políticas Públicas y Salud Comunitaria en la Ruralidad",
    "Pedagogías Para la Paz Territorial",
    "Práctica Pedagógica II: Planes de Vida Comunitarios",
    "Comunicación en Segunda Lengua I",
    "Economía Social y Solidaria, de Autoconsumo y Familiar",
    "Formas organizativas y asuntos jurídicos para la gobernanza de las comunidades rurales",
    "Educación para la Salud Rural Colectiva y Ambiental",
    "Educación, inclusión y discapacidad en la ruralidad",
    "Práctica Pedagógica III: Procesos de Innovación y Creación en la Ruralidad",
    "Comunicación en Segunda Lengua II",
    "Seminario de Profundización I",
    "Electiva de Profundización I",
    "Práctica Pedagógica IV: Propuesta Creativa Comunitaria I",
    "Formación Ciudadana y Constitucional",
    "Comunicación en Segunda Lengua III",
    "Seminario de Profundización II",
    "Electiva de Profundización II",
    "Práctica Pedagógica V: Propuesta Creativa Comunitaria II",
    "Comunicación en Segunda Lengua IV",
    "Seminario de Profundización III",
    "Electiva de Profundización III",
    "Práctica Pedagógica VI: Propuesta Creativa Comunitaria III-Trabajo de Grado",
    "Comunicación en Segunda Lengua V"
]
creditos = [3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 4, 2, 3, 3, 3, 3, 4, 2, 3, 3, 3, 3, 4, 2, 3, 3, 6, 2, 2, 3, 3, 6, 2, 3, 3, 6, 2]
print(len(nombres), len(creditos))
for nombre, credito in zip(nombres, creditos):
    print(f"""
    {{
        "nota": 5.0,
        "creditos": {credito},
        "nombre": "{nombre}",
        "codigo": "",
        "tipologia": "libre_eleccion",
        "semestre": 1,
        "prerrequisitos": null,
        "estado": "aprobada"
    }},
    """, end="")